### ISSUE TITLE
fix POT storage

### ISSUE THREAD

**Issue by chenel** [DUNE/ND_CAFMaker#36]
current files write out NaN POT.  This needs to be fixed!

**Comment by chenel** [comment]
The problem has a bit of complexity to it, in that in the case where we're matching across detectors, the total POT of all spills of all input files won't be the same as the POT corresponding to the intersection of the matched spills.  Probably the solution here is:

- Set up a CAFMaker parameter, and implement a choice, whether to write out unmatched spills when there are multiple reco streams involved
- Eliminate the global POT value in the metadata tree?  Or at least don't write anything out unless all the triggers are matched (or unmatched ones are thrown out)
- Force reco pathways to propagate exposure info, and check that matches when matching spills.  Copy it into the `StandardRecord` entries.

**Comment by chenel** [comment]
I think the solution will likely come in two stages.  First, we'll add a parameter to the CAFMaker with a fixed POT/spill that we can use in the short term as a stopgap.  The longer term solution is likely along the lines described above---though it may be possible to have the CAFMaker be a single interface to the IFBeam database.  Depends on whether we want CAFMaker to handle data & MC differently...

**Comment by chenel** [comment]
@mjkramer and @sindhu-ku are going to work on a first pass on this for 2x2 files.

**Comment by sindhu-ku** [comment]
Fixed in https://github.com/DUNE/ND_CAFMaker/pull/89 through IFBeam interface
