### ISSUE TITLE
Duplicate and "phantom" G4 true particles in MC dataset

### ISSUE THREAD

**Issue by cuddandr** [DUNE/ND_CAFMaker#71]
The list of true secondary particles contains duplicate entries/particles with (apparently) valid information (G4ID, PDG, etc.) and some "phantom particles". These phantom particles are filled with their default values giving a G4ID of -1 and a PDG code of 0 (along with a NaN momentum). Reconstructed particles occasionally have these phantom particles as their true particle match.

This can be seen by iterating over the `sr->mc.nu[idx].sec` vector in the CAFs for a given truth interaction, and can be seen in the MiniRun5 beta2a CAFs. So far this has only been seen in the true secondary particle list. Examples of duplicated G4 particles and these "phantom particles" can be seen in the attached output with the files and spill numbers.

[caf_bug_output_20240626.txt](https://github.com/user-attachments/files/16070801/caf_bug_output_20240626.txt)

**Comment by sindhu-ku** [comment]
Can you check if this changed anything for number of primaries as well?

**Comment by noeroy** [comment]
Fixed with PR #77
